{% set version = "18.0.1" %}

package:
  name: keyring
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/keyring/keyring-{{ version }}.tar.gz
  sha256: 67d6cc0132bd77922725fae9f18366bb314fd8f95ff4d323a4df41890a96a838

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - keyring = keyring.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
    - setuptools >=34.4
  run:
    - python
    - entrypoints

    - importlib-metadata  # [py<38]
    - jeepney >=0.4.2  # [linux]
    - pywin32-ctypes !=0.1.0,!=0.1.1  # [win]
    - secretstorage  # [linux and py>=35]
    - secretstorage <3  # [linux and py<35]


test:
  imports:
    - keyring
    - keyring.backends
    - keyring.util
  commands:
    - keyring --help

about:
  home: https://github.com/jaraco/keyring
  license: Python Software Foundation or MIT
  license_file: LICENSE
  summary: 'Store and access your passwords safely'

extra:
  recipe-maintainers:
    - ericdill
    - licode
    - tacaswell
    - ccordoba12
